name: Backend CI

on:
  push:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22]  # keep your version; switch to 20 LTS if you hit tooling issues

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      - name: Stop pm2 (if running)
        run: pm2 stop all || true

      # --- Backend ---
      - name: Install Backend Dependencies (npm)
        working-directory: ./backend
        run: npm ci

      # --- Frontend ---
      - name: Install Frontend Dependencies (npm)
        working-directory: ./frontend
        run: npm ci

      - name: Build Frontend
        working-directory: ./frontend
        env:
          CI: false
        run: npm run build

      # --- Tests ---
      - name: Run Backend Tests
        working-directory: ./backend
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
          CI: true
        run: npm test -- --ci

      # --- Runtime env / pm2 ---
      - name: Write .env for backend runtime
        working-directory: ./backend
        run: |
          printf "%s\n" "${{ secrets.PROD }}" > .env

      - name: Start pm2 apps
        run: |
          pm2 start all || true
          pm2 restart all || true
